### PR TITLE
Revert non-empty-string changes and add regression test

### LINKED ISSUE #85: False positive on `Assert::upper()` always evaluates as true
Hello I just updated phpstan-webmozart-assert to v1.0.7 and my codebase started reporting this error:

```
Call to static method Webmozart\Assert\Assert::upper() with non-empty-string will always evaluate to true.
```

It's failing in the following class construct
```
final class CityCode
{
    private function __construct(private string $cityCode)
    {
    }

    public static function fromString(string $cityCode) : self
    {
        Assert::length($cityCode, 3);
        Assert::upper($cityCode);

        return new self($cityCode);
    }
}
```

I'm not using the non-empty-string type assertion anywhere so it must be resolved from the length assertion, however that doesn't ensure what upper is doing.

Thank you for looking into this, and all your great work.

### PR DESCRIPTION
**Pull request by herndlm**
Closes #85
Includes #88
Reverts 19b869e1506c6a63fcaa05cd0c213abf0e9ca9b5 and 90091355b55dab2ad45fa1cf88b7114523940c09

Adapts the `ImpossibleCheckTypeMethodCallRuleTest` to use `phpstan-strict-rules` so that `checkAlwaysTrueCheckTypeFunctionCall` is enabled and we can actually regression test #85

Sorry all for all the troubles caused :/

### CODE REVIEW

File: tests/Type/WebMozartAssert/ImpossibleCheckTypeMethodCallRuleTest.php [hunk 1]
```diff
@@ -18,6 +18,8 @@ protected function getRule(): Rule
 
 	public function testExtension(): void
 	{
+		$this->analyse([__DIR__ . '/data/bug-85.php'], []);
```
Comment (ondrejmirtes) [inline tests/Type/WebMozartAssert/ImpossibleCheckTypeMethodCallRuleTest.php]: Please add this in a separate test case. The difference is that when bug-85.php fails, we'll also know about failures from impossible-check.php.

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]

**Comment by ondrejmirtes** [comment]
Perfect, gonna release it right away. We can then talk about the solution :) Thank you.

**Review by ondrejmirtes — APPROVED** [review]

**Comment by herndlm** [comment]
Thx Ondrej for the quick review, merge and release!

Let me know if you have any ideas already how to move forward with the type problems and `ImpossibleCheckTypeMethodCallRule`. In the context of this extension this seems to be making problems sometimes, e.g. #68 too for example (with the modified rule test here this can be reproduced now too).

In general I guess this starts to get problematic if the assertions do more than simple type checks (e.g. `assertCount`, `assertLength` or `assertUuid`). But I have no idea how to solve that right now unfortunately. It all comes down to phpstan's core `ImpossibleCheckTypeHelper` that finds the specified types and the rule that then finds out that no more information type-wise (non-empty-string is still going to be a non-empty-string after checking that it is a valid UUID for example) is added.
